### ISSUE TITLE
"detail": "Authentication credentials were not provided."

### ISSUE THREAD

**Issue by yashpatel5566789** [JuanBenitezDev/django-rest-framework-crud#5]
hey i just try to run ur reset api but it didnt work can u help to fix it

**Comment by JuanBenitez97** [comment]
Sorry for late, I  dont know what you mean with reset api, but it seems you have not created an user with this endpoint `POST http://127.0.0.1:8000/rest-auth/registration/ username="USERNAME" password1="PASSWORD" password2="PASSWORD"`
