### ISSUE TITLE
Can I add custom response after login?

### ISSUE THREAD

**Issue by malvikiran** [JuanBenitezDev/django-rest-framework-crud#9]
Can I add custom response?

Currently After login 
```
{
    "key": "4cada2ed9ccdfa78313fcfba075bf87ecb9d05b50"
}
```

Getting above response

But If I want to add more parameters like
```
{
    "key": "4cada2ed9ccdfa78313fcfba075bf87ecb9d05b5",
    "User" {
        "name": "XXCD",
        "age": 20
    }
}
```

**Comment by JuanBenitez97** [comment]
Yes, you can create a CustomLoginView subclassing the LoginView provided by rest_auth, but I recommend you use djangorestframework jwt authentication
